name: Hello World Workflow

on:
  push: # コードがPushされた際にトリガー
    branches:
      - main # mainブランチに限定

jobs:
  say_hello:
    runs-on: ubuntu-latest # GitHubが提供するUbuntuランナーを使用
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # コードをチェックアウト

      - name: Say Hello
        run: echo "Hello, World!" # シンプルにメッセージを出力

      - name: Custom Greeting
        run: echo "Hello, ${{ github.actor }}!" # 実行ユーザーの名前を取得

